version: '3'
services:
  postgresql:
    image: postgres:9.3
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
    ports:
        - "5433:5432"
    container_name: news_db
  worker_ria:
    build: .
    command:  bash -c "python3 ./parser.py ria.ru"
    container_name: worker_ria
    volumes:
      - .\ais\:/code/ais
    depends_on:
      - postgresql

volumes:
  pgdata: {}
